name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: 'stable'  # or use specific version like '3.19.5'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test